version: '2'
services:
  rapsi-car:
    image: u03013112/raspi-car:1.0
    container_name: raspi-car
    tty: true
    restart: always
    ports:
      - 5000:5000
      - 8888:8888
    privileged: true
    volumes:
      - /proc:/host/proc
      - ./:/usr/src/app