version: '2'
services:
  ddns-local:
    image: u03013112/rapsi-car:1.0
    container_name: rapsi-car
    tty: true
    restart: always
    ports:
      - 5000:5000
      - 8888:8888
    privileged: true
    volumes:
      - /proc:/host/proc